spring.application.name=springboot

spring.security.user.name=versatec
spring.security.user.password=4a34a375-d3f9-45bf-b0c0-7e6421fa0972

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

file.asset-dir=assets
file.upload-dir=uploads
file.download-dir=downloads

app.url=https://versign.versatecnologia.com.br

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v1/api-docs

serpro.auth.client.id=SEU_CLIENT_ID
serpro.auth.client.secret=SEU_CLIENT_SECRET
serpro.auth.token.url=https://gateway.apiserpro.serpro.gov.br/token