spring.application.name=springboot

spring.security.user.name=versatec
spring.security.user.password=4a34a375-d3f9-45bf-b0c0-7e6421fa0972

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

file.asset-dir=assets
file.upload-dir=uploads
file.download-dir=downloads

app.url=https://versign.versatecnologia.com.br

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v1/api-docs

// Time Stamp Authority (TSA) configuration
tsa.url=https://gateway.apiserpro.serpro.gov.br/apitimestamp/v1/stamps
serpro.auth.consumer.key=jIXkCCyjmstrfZrdfYpAVUDoBwwa
serpro.auth.consumer.secret=zok1bpUdC3J7prqySh3C3JZHaQga
serpro.auth.token.url=https://gateway.apiserpro.serpro.gov.br/token

# Mostra logs detalhados do Demoiselle
#ogging.level.org.demoiselle.signer=DEBUG

# Mostra o tráfego das bibliotecas Apache HTTP (usadas internamente)
#logging.level.org.apache.http=DEBUG
#logging.level.org.apache.http.wire=DEBUG